---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskmaster
{{ if eq .Values.clusterType "openshift" }}
---
kind: RoleBinding
apiVersion: authorization.openshift.io/v1
groupNames:
- taskmastersadmins
metadata:
  name: taskmaster-role-binding
subjects:
- kind: ServiceAccount
  name: taskmaster
roleRef:
  name: admin
userNames:
- taskmaster
{{ else }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: taskmaster
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - pods/log
  - pods/status
  verbs:
  - get
  - list
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: taskmaster-role-binding
subjects:
- kind: ServiceAccount
  name: taskmaster
roleRef:
  kind: Role
  name: taskmaster
  apiGroup: rbac.authorization.k8s.io
{{ end }}

